# pre-commit is a framework for managing multi-language pre-commit hooks
# run `pre-commit install` to install pre-commit git hook.
# https://pre-commit.com
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.2.1" # Use the sha / tag you want to point at
    hooks:
      - id: prettier
